# Generated by Django 5.0.1 on 2024-01-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
