# Generated by Django 5.0.1 on 2024-02-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_teams_count_teams_members_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='team_profile/'),
        ),
    ]
