# Generated by Django 5.0.1 on 2024-02-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='https://img.icons8.com/pulsar-line/48/user.png', null=True, upload_to='profile_photos/'),
        ),
    ]
